### ISSUE TITLE
Source code for generating ReST output

### ISSUE THREAD

**Issue by wshanks** [pekopeko1/xv6-book-en#1]
It has been a long time since this was updated, but is there any chance you could share the source code that you used to convert the original troff content of the book into ReStructed Text for Sphinx?

**Comment by pekopeko1** [comment]
@willsALMANJ 
Thank you for commenting.
I converted it manually, so I'm afraid that there is no source code to convert the original contents into ReST format.

**Comment by wshanks** [comment]
Ah, okay. Thanks for responding! I was not familiar with troff but the conversion doesn't look too bad.
